-- User devices registry for per-device linking (Shizuku / root pairing).
create table if not exists public.user_devices (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  device_sha text not null,
  auth_provider text not null default 'supabase',
  created_at timestamp with time zone default now(),
  unique(user_id, device_sha)
);

create index if not exists idx_user_devices_user on public.user_devices(user_id);
create index if not exists idx_user_devices_sha on public.user_devices(device_sha);

alter table public.user_devices enable row level security;

-- Users can fully manage their own devices
drop policy if exists "Users can manage own devices" on public.user_devices;
create policy "Users can manage own devices" on public.user_devices
  for all to anon, authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
