-- RLS hardening for the tables used by the app's chat / task / settings flows.
-- Each user may only read/write their own rows. This migration is safe to run
-- on databases where these tables were already created manually (all
-- statements are idempotent).

-- ─── chat_sessions ──────────────────────────────────────────────────────────
create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.chat_sessions enable row level security;

drop policy if exists "Users can manage own chat sessions" on public.chat_sessions;
create policy "Users can manage own chat sessions" on public.chat_sessions
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ─── chat_messages ──────────────────────────────────────────────────────────
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid references public.chat_sessions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role text not null,
  content text not null default '',
  action_result jsonb,
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "Users can manage own chat messages" on public.chat_messages;
create policy "Users can manage own chat messages" on public.chat_messages
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ─── saved_skills ───────────────────────────────────────────────────────────
create table if not exists public.saved_skills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  task text not null default '',
  task_keywords text[] not null default '{}',
  steps jsonb not null default '[]',
  success_count int not null default 0,
  fail_count int not null default 0,
  last_used timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.saved_skills enable row level security;

drop policy if exists "Users can manage own saved skills" on public.saved_skills;
create policy "Users can manage own saved skills" on public.saved_skills
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ─── task_history ───────────────────────────────────────────────────────────
create table if not exists public.task_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  goal text not null default '',
  status text not null default '',
  total_tokens int not null default 0,
  steps_taken int not null default 0,
  trace text,
  created_at timestamptz not null default now()
);

alter table public.task_history enable row level security;

drop policy if exists "Users can manage own task history" on public.task_history;
create policy "Users can manage own task history" on public.task_history
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ─── user_settings ──────────────────────────────────────────────────────────
create table if not exists public.user_settings (
  user_id uuid references public.profiles(id) on delete cascade primary key,
  settings jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.user_settings enable row level security;

drop policy if exists "Users can manage own settings" on public.user_settings;
create policy "Users can manage own settings" on public.user_settings
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ─── Remove anon access from already-applied policies ───────────────────────
-- api_keys / user_devices were originally created with `for all to anon,
-- authenticated`. The `anon` role must never reach user-owned rows.

drop policy if exists "Users can manage own API keys" on public.api_keys;
create policy "Users can manage own API keys" on public.api_keys
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage own devices" on public.user_devices;
create policy "Users can manage own devices" on public.user_devices
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
